---

- name: install packetbeat
  yum:
    name: https://artifacts.elastic.co/downloads/beats/packetbeat/packetbeat-5.4.2-x86_64.rpm
    state: present

- name: copy packetbeat.yml
  copy: src=packetbeat.yml dest=/etc/packetbeat owner=root group=root mode=0644 backup=yes

- name: start packetbeat
  service:
    name: packetbeat
    enabled: yes
    masked: no
    state: started
